#!/usr/bin/env python3
"""
train_model.py  –  Train an anomaly detection model and export to ONNX.

Usage:
    python train_model.py --dataset dataset.csv --output ../data/anomaly_model.onnx

Trains a Gradient Boosted Tree (XGBoost or sklearn) on the 38-feature vectors
generated by generate_dataset.py.  Exports the trained model in ONNX format
for consumption by the C++ AnomalyDetector via ONNX Runtime.

Requirements:
    pip install numpy pandas scikit-learn xgboost skl2onnx onnx onnxruntime
"""

import argparse
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score, accuracy_score
)
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# ============================================================================
# Model choices (in order of preference)
# ============================================================================

def try_xgboost():
    """Try XGBoost first – best performance for tabular data."""
    try:
        from xgboost import XGBClassifier
        model = XGBClassifier(
            n_estimators=200,
            max_depth=6,
            learning_rate=0.1,
            subsample=0.8,
            colsample_bytree=0.8,
            eval_metric="logloss",
            use_label_encoder=False,
            random_state=42,
        )
        return model, "XGBoost"
    except ImportError:
        return None, None


def try_gradient_boosting():
    """Fallback to sklearn's GradientBoostingClassifier."""
    from sklearn.ensemble import GradientBoostingClassifier
    model = GradientBoostingClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        random_state=42,
    )
    return model, "GradientBoosting"


def try_random_forest():
    """Last resort – simpler but still decent."""
    from sklearn.ensemble import RandomForestClassifier
    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        random_state=42,
    )
    return model, "RandomForest"


# ============================================================================
# ONNX export
# ============================================================================

def export_sklearn_to_onnx(pipeline, output_path: str, n_features: int):
    """Export a sklearn Pipeline to ONNX format."""
    from skl2onnx import convert_sklearn
    from skl2onnx.common.data_types import FloatTensorType

    initial_type = [("features", FloatTensorType([None, n_features]))]
    onnx_model = convert_sklearn(
        pipeline,
        initial_types=initial_type,
        target_opset=13,
        options={id(pipeline): {"zipmap": False}},
    )
    with open(output_path, "wb") as f:
        f.write(onnx_model.SerializeToString())
    print(f"ONNX model exported to {output_path}")


def export_xgboost_to_onnx(pipeline, output_path: str, n_features: int):
    """Export an XGBoost pipeline to ONNX."""
    try:
        from skl2onnx import convert_sklearn
        from skl2onnx.common.data_types import FloatTensorType
        # skl2onnx supports XGBoost via onnxmltools converters
        try:
            import onnxmltools  # noqa: F401 – registers the XGBoost converter
        except ImportError:
            pass

        initial_type = [("features", FloatTensorType([None, n_features]))]
        onnx_model = convert_sklearn(
            pipeline,
            initial_types=initial_type,
            target_opset=13,
            options={id(pipeline): {"zipmap": False}},
        )
        with open(output_path, "wb") as f:
            f.write(onnx_model.SerializeToString())
        print(f"ONNX model exported to {output_path}")
    except Exception as e:
        print(f"skl2onnx export failed ({e}), trying onnxmltools directly...")
        try:
            import onnxmltools
            from onnxmltools.convert.common.data_types import FloatTensorType
            initial_type = [("features", FloatTensorType([None, n_features]))]
            onnx_model = onnxmltools.convert_xgboost(
                pipeline.named_steps["classifier"],
                initial_types=initial_type,
            )
            with open(output_path, "wb") as f:
                f.write(onnx_model.SerializeToString())
            print(f"ONNX model exported to {output_path}")
        except Exception as e2:
            print(f"ERROR: Could not export to ONNX: {e2}")
            print("Install: pip install skl2onnx onnxmltools")
            sys.exit(1)


def verify_onnx(onnx_path: str, X_sample: np.ndarray, expected_probs: np.ndarray):
    """Verify the ONNX model produces similar outputs to the original."""
    try:
        import onnxruntime as ort
        sess = ort.InferenceSession(onnx_path)
        input_name = sess.get_inputs()[0].name
        results = sess.run(None, {input_name: X_sample[:5].astype(np.float32)})

        print(f"\nONNX verification (first 5 samples):")
        print(f"  Input shape:  {X_sample[:5].shape}")
        print(f"  Outputs: {len(results)} tensors")
        for i, r in enumerate(results):
            arr = np.array(r)
            print(f"  Output[{i}] shape={arr.shape}, dtype={arr.dtype}")
            if arr.ndim >= 1 and arr.shape[-1] >= 2:
                print(f"  Malicious probs (ONNX):   {arr[:5, 1]}")
                print(f"  Malicious probs (sklearn): {expected_probs[:5, 1]}")
        print("ONNX verification passed!")
    except ImportError:
        print("onnxruntime not installed – skipping verification")
    except Exception as e:
        print(f"ONNX verification warning: {e}")


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description="Train anomaly detection model")
    parser.add_argument("--dataset", required=True, help="Path to dataset.csv")
    parser.add_argument("--output", default="../data/anomaly_model.onnx",
                        help="Output ONNX model path")
    parser.add_argument("--test-size", type=float, default=0.2,
                        help="Test split ratio (default 0.2)")
    args = parser.parse_args()

    # Load dataset
    print(f"Loading dataset from {args.dataset}...")
    df = pd.read_csv(args.dataset)
    print(f"  {len(df)} samples, {df['label'].value_counts().to_dict()}")

    if len(df) < 20:
        print("WARNING: Very small dataset. Model quality will be poor.")
        print("Aim for at least 500+ samples of each class for decent results.")

    X = df.drop(columns=["label"]).values.astype(np.float32)
    y = df["label"].values

    n_features = X.shape[1]
    print(f"  {n_features} features")

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, random_state=42, stratify=y
    )
    print(f"  Train: {len(X_train)}, Test: {len(X_test)}")

    # Pick the best available model
    model, model_name = try_xgboost()
    if model is None:
        model, model_name = try_gradient_boosting()
    print(f"\nUsing model: {model_name}")

    # Build pipeline with scaling
    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", model),
    ])

    # Cross-validation on training set
    print("\nRunning 5-fold cross-validation...")
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring="roc_auc")
    print(f"  CV ROC-AUC: {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")

    # Train final model
    print("\nTraining final model...")
    pipeline.fit(X_train, y_train)

    # Evaluate on test set
    y_pred = pipeline.predict(X_test)
    y_prob = pipeline.predict_proba(X_test)

    print(f"\n{'='*60}")
    print(f"TEST SET RESULTS ({model_name})")
    print(f"{'='*60}")
    print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
    print(f"ROC-AUC:   {roc_auc_score(y_test, y_prob[:, 1]):.4f}")
    print(f"\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["Benign", "Malicious"]))
    print(f"Confusion Matrix:")
    cm = confusion_matrix(y_test, y_pred)
    print(f"  TN={cm[0,0]}  FP={cm[0,1]}")
    print(f"  FN={cm[1,0]}  TP={cm[1,1]}")

    # Feature importance
    classifier = pipeline.named_steps["classifier"]
    if hasattr(classifier, "feature_importances_"):
        importances = classifier.feature_importances_
        feature_names = df.drop(columns=["label"]).columns
        sorted_idx = np.argsort(importances)[::-1]
        print(f"\nTop 10 features by importance:")
        for i in range(min(10, len(sorted_idx))):
            idx = sorted_idx[i]
            print(f"  {feature_names[idx]:30s} {importances[idx]:.4f}")

    # Export to ONNX
    print(f"\nExporting to ONNX: {args.output}")
    output_dir = Path(args.output).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    if model_name == "XGBoost":
        export_xgboost_to_onnx(pipeline, args.output, n_features)
    else:
        export_sklearn_to_onnx(pipeline, args.output, n_features)

    # Verify ONNX output matches sklearn
    verify_onnx(args.output, X_test, y_prob)

    print(f"\nDone! Model saved to {args.output}")
    print(f"Copy this file to data/anomaly_model.onnx in the build directory.")


if __name__ == "__main__":
    main()
